### ISSUE TITLE
TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by AxDSan** [doyler/SecurityTools#1]
PythonShellcode.py - Whenever I try to execute the shellcode, it shows up that error. It happens on bytearray()

**Comment by doyler** [comment]
Ah, yes, I forgot about that.

This code will work in Python 2.7, but will error out in Python 3.

The reason for this is that bytearray requires a second argument so that it can be encoded in bytes.

In that case, adding `, 'utf8'` to the end of the string should work just fine.

Let me know if that fixes your issue!

**Comment by AxDSan** [comment]
It worked, Thank you 💃
